var globalData = {
    "leistungen":[{ "id": "1", "leistung": "Kaufberatung", "group": "Beratung" }, { "id": "2", "leistung": "Verkaufsberatung", "group": "Beratung" }, { "id": "3", "leistung": "Bauabnahme", "group": "Beratung" }, { "id": "4", "leistung": "Wohnraumvermessung", "group": "Beratung" }, { "id": "5", "leistung": "Feuchtemessung", "group": "Beratung" }, { "id": "6", "leistung": "Schimmelpilzanalysen", "group": "Beratung" }, { "id": "7", "leistung": "Energieausweis", "group": "Beratung" }, { "id": "8", "leistung": "Kurzgutachten", "group": "Immobilienbewertung" }, { "id": "9", "leistung": "Verkehrswertgutachten", "group": "Immobilienbewertung" }, { "id": "10", "leistung": "Mietwertgutachten", "group": "Immobilienbewertung" }, { "id": "11", "leistung": "Beleihungswertgutachten", "group": "Immobilienbewertung" }, { "id": "12", "leistung": "Portfolioanalyse", "group": "Immobilienbewertung" }, { "id": "13", "leistung": "Gutachten für Entschädigung", "group": "Immobilienbewertung" }, { "id": "14", "leistung": "Bauschäden", "group": "Begutachtung" }, { "id": "15", "leistung": "Baumängel", "group": "Begutachtung" }, { "id": "16", "leistung": "Schimmelpilzschäden", "group": "Begutachtung" }, { "id": "17", "leistung": "Versicherungsschäden", "group": "Begutachtung" }, { "id": "18", "leistung": "Beweissicherung", "group": "Begutachtung" }, { "id": "19", "leistung": "Prüfung von Schadensgutachten", "group": "Begutachtung" }, { "id": "20", "leistung": "Planungsleistungen", "group": "Planung" }, { "id": "21", "leistung": "Prüfung von Planungsleistungen", "group": "Planung" }, { "id": "22", "leistung": "Bauleitung", "group": "Planung" }, { "id": "23", "leistung": "Baubegleitende Qualitätsüberwachung", "group": "Planung" }, { "id": "24", "leistung": "SiGeKo", "group": "Planung" }, { "id": "25", "leistung": "Übergabeprotokoll", "group": "Beratung" }, { "id": "26", "leistung": "Kanaldichtheitsprüfung", "group": "Begutachtung" }, { "id": "27", "leistung": "Gebäudeschadstoffe", "group": "Begutachtung" }, { "id": "28", "leistung": "Bodengutachten", "group": "Begutachtung" }, { "id": "29", "leistung": "Sanierungsberatung", "group": "Beratung" }, { "id": "30", "leistung": "Schadensberatung", "group": "Beratung" }],
    "schwerpunkte":[
        {
            "id":1,
            "value":"Schäden an Gebäuden"
        },
        {
            "id":2,
            "value":"Immobilienbewertung"
        },
        {
            "id":3,
            "value":"Bauüberwachung, Ausschreibung + Vergabe"
        },
        {
            "id":4,
            "value":"Projektierung"
        },
        {
            "id":5,
            "value":"Erbbaurecht"
        },
        {
            "id":6,
            "value":"Windenergieanlagen"
        },
        {
            "id":7,
            "value":"Baubegleitung/Gutachten Heizung/Lüftung/Sanitär"
        },
        {
            "id":8,
            "value":"Kraft-Wärme-Kopplungssysteme"
        },
        {
            "id":9,
            "value":"Energieberatung KFW/BAFA"
        },
        {
            "id":10,
            "value":"Brandschutz"
        }
    ],
    "countries":[
        {
            "name":"Deutschland",
            "code":"DE"
        },
        {
            "name":"Afghanistan",
            "code":"AF"
        },
        {
            "name":"Åland",
            "code":"AX"
        },
        {
            "name":"Albanien",
            "code":"AL"
        },
        {
            "name":"Algerien",
            "code":"DZ"
        },
        {
            "name":"Amerikanisch-Samoa",
            "code":"AS"
        },
        {
            "name":"Andorra",
            "code":"AD"
        },
        {
            "name":"Angola",
            "code":"AO"
        },
        {
            "name":"Anguilla",
            "code":"AI"
        },
        {
            "name":"Antarktika",
            "code":"AQ"
        },
        {
            "name":"Antigua und Barbuda",
            "code":"AG"
        },
        {
            "name":"Argentinien",
            "code":"AR"
        },
        {
            "name":"Armenien",
            "code":"AM"
        },
        {
            "name":"Aruba",
            "code":"AW"
        },
        {
            "name":"Australien",
            "code":"AU"
        },
        {
            "name":"Österreich",
            "code":"AT"
        },
        {
            "name":"Aserbaidschan",
            "code":"AZ"
        },
        {
            "name":"Bahamas",
            "code":"BS"
        },
        {
            "name":"Bahrain",
            "code":"BH"
        },
        {
            "name":"Bangladesch",
            "code":"BD"
        },
        {
            "name":"Barbados",
            "code":"BB"
        },
        {
            "name":"Weißrussland",
            "code":"BY"
        },
        {
            "name":"Belgien",
            "code":"BE"
        },
        {
            "name":"Belize",
            "code":"BZ"
        },
        {
            "name":"Benin",
            "code":"BJ"
        },
        {
            "name":"Bermuda",
            "code":"BM"
        },
        {
            "name":"Bhutan",
            "code":"BT"
        },
        {
            "name":"Bolivien",
            "code":"BO"
        },
        {
            "name":"Bonaire, Sint Eustatius und Saba",
            "code":"BQ"
        },
        {
            "name":"Bosnien und Herzegowina",
            "code":"BA"
        },
        {
            "name":"Botswana",
            "code":"BW"
        },
        {
            "name":"Bouvetinsel",
            "code":"BV"
        },
        {
            "name":"Brasilien",
            "code":"BR"
        },
        {
            "name":"Britisches Territorium im Indischen Ozean",
            "code":"IO"
        },
        {
            "name":"Kleinere Inselbesitzungen der Vereinigten Staaten",
            "code":"UM"
        },
        {
            "name":"Britische Jungferninseln",
            "code":"VG"
        },
        {
            "name":"Amerikanische Jungferninseln",
            "code":"VI"
        },
        {
            "name":"Brunei",
            "code":"BN"
        },
        {
            "name":"Bulgarien",
            "code":"BG"
        },
        {
            "name":"Burkina Faso",
            "code":"BF"
        },
        {
            "name":"Burundi",
            "code":"BI"
        },
        {
            "name":"Kambodscha",
            "code":"KH"
        },
        {
            "name":"Kamerun",
            "code":"CM"
        },
        {
            "name":"Kanada",
            "code":"CA"
        },
        {
            "name":"Kap Verde",
            "code":"CV"
        },
        {
            "name":"Kaimaninseln",
            "code":"KY"
        },
        {
            "name":"Zentralafrikanische Republik",
            "code":"CF"
        },
        {
            "name":"Tschad",
            "code":"TD"
        },
        {
            "name":"Chile",
            "code":"CL"
        },
        {
            "name":"China",
            "code":"CN"
        },
        {
            "name":"Weihnachtsinsel",
            "code":"CX"
        },
        {
            "name":"Kokosinseln",
            "code":"CC"
        },
        {
            "name":"Kolumbien",
            "code":"CO"
        },
        {
            "name":"Union der Komoren",
            "code":"KM"
        },
        {
            "name":"Kongo",
            "code":"CG"
        },
        {
            "name":"Kongo (Dem. Rep.)",
            "code":"CD"
        },
        {
            "name":"Cookinseln",
            "code":"CK"
        },
        {
            "name":"Costa Rica",
            "code":"CR"
        },
        {
            "name":"Kroatien",
            "code":"HR"
        },
        {
            "name":"Kuba",
            "code":"CU"
        },
        {
            "name":"Curaçao",
            "code":"CW"
        },
        {
            "name":"Zypern",
            "code":"CY"
        },
        {
            "name":"Tschechische Republik",
            "code":"CZ"
        },
        {
            "name":"Dänemark",
            "code":"DK"
        },
        {
            "name":"Dschibuti",
            "code":"DJ"
        },
        {
            "name":"Dominica",
            "code":"DM"
        },
        {
            "name":"Dominikanische Republik",
            "code":"DO"
        },
        {
            "name":"Ecuador",
            "code":"EC"
        },
        {
            "name":"Ägypten",
            "code":"EG"
        },
        {
            "name":"El Salvador",
            "code":"SV"
        },
        {
            "name":"Äquatorial-Guinea",
            "code":"GQ"
        },
        {
            "name":"Eritrea",
            "code":"ER"
        },
        {
            "name":"Estland",
            "code":"EE"
        },
        {
            "name":"Äthiopien",
            "code":"ET"
        },
        {
            "name":"Falklandinseln",
            "code":"FK"
        },
        {
            "name":"Färöer-Inseln",
            "code":"FO"
        },
        {
            "name":"Fidschi",
            "code":"FJ"
        },
        {
            "name":"Finnland",
            "code":"FI"
        },
        {
            "name":"Frankreich",
            "code":"FR"
        },
        {
            "name":"Französisch Guyana",
            "code":"GF"
        },
        {
            "name":"Französisch-Polynesien",
            "code":"PF"
        },
        {
            "name":"Französische Süd- und Antarktisgebiete",
            "code":"TF"
        },
        {
            "name":"Gabun",
            "code":"GA"
        },
        {
            "name":"Gambia",
            "code":"GM"
        },
        {
            "name":"Georgien",
            "code":"GE"
        },
        {
            "name":"Ghana",
            "code":"GH"
        },
        {
            "name":"Gibraltar",
            "code":"GI"
        },
        {
            "name":"Griechenland",
            "code":"GR"
        },
        {
            "name":"Grönland",
            "code":"GL"
        },
        {
            "name":"Grenada",
            "code":"GD"
        },
        {
            "name":"Guadeloupe",
            "code":"GP"
        },
        {
            "name":"Guam",
            "code":"GU"
        },
        {
            "name":"Guatemala",
            "code":"GT"
        },
        {
            "name":"Guernsey",
            "code":"GG"
        },
        {
            "name":"Guinea",
            "code":"GN"
        },
        {
            "name":"Guinea-Bissau",
            "code":"GW"
        },
        {
            "name":"Guyana",
            "code":"GY"
        },
        {
            "name":"Haiti",
            "code":"HT"
        },
        {
            "name":"Heard und die McDonaldinseln",
            "code":"HM"
        },
        {
            "name":"Heiliger Stuhl",
            "code":"VA"
        },
        {
            "name":"Honduras",
            "code":"HN"
        },
        {
            "name":"Hong Kong",
            "code":"HK"
        },
        {
            "name":"Ungarn",
            "code":"HU"
        },
        {
            "name":"Island",
            "code":"IS"
        },
        {
            "name":"Indien",
            "code":"IN"
        },
        {
            "name":"Indonesien",
            "code":"ID"
        },
        {
            "name":"Elfenbeinküste",
            "code":"CI"
        },
        {
            "name":"Iran",
            "code":"IR"
        },
        {
            "name":"Irak",
            "code":"IQ"
        },
        {
            "name":"Irland",
            "code":"IE"
        },
        {
            "name":"Insel Man",
            "code":"IM"
        },
        {
            "name":"Israel",
            "code":"IL"
        },
        {
            "name":"Italien",
            "code":"IT"
        },
        {
            "name":"Jamaika",
            "code":"JM"
        },
        {
            "name":"Japan",
            "code":"JP"
        },
        {
            "name":"Jersey",
            "code":"JE"
        },
        {
            "name":"Jordanien",
            "code":"JO"
        },
        {
            "name":"Kasachstan",
            "code":"KZ"
        },
        {
            "name":"Kenia",
            "code":"KE"
        },
        {
            "name":"Kiribati",
            "code":"KI"
        },
        {
            "name":"Kuwait",
            "code":"KW"
        },
        {
            "name":"Kirgisistan",
            "code":"KG"
        },
        {
            "name":"Laos",
            "code":"LA"
        },
        {
            "name":"Lettland",
            "code":"LV"
        },
        {
            "name":"Libanon",
            "code":"LB"
        },
        {
            "name":"Lesotho",
            "code":"LS"
        },
        {
            "name":"Liberia",
            "code":"LR"
        },
        {
            "name":"Libyen",
            "code":"LY"
        },
        {
            "name":"Liechtenstein",
            "code":"LI"
        },
        {
            "name":"Litauen",
            "code":"LT"
        },
        {
            "name":"Luxemburg",
            "code":"LU"
        },
        {
            "name":"Macao",
            "code":"MO"
        },
        {
            "name":"Mazedonien",
            "code":"MK"
        },
        {
            "name":"Madagaskar",
            "code":"MG"
        },
        {
            "name":"Malawi",
            "code":"MW"
        },
        {
            "name":"Malaysia",
            "code":"MY"
        },
        {
            "name":"Malediven",
            "code":"MV"
        },
        {
            "name":"Mali",
            "code":"ML"
        },
        {
            "name":"Malta",
            "code":"MT"
        },
        {
            "name":"Marshallinseln",
            "code":"MH"
        },
        {
            "name":"Martinique",
            "code":"MQ"
        },
        {
            "name":"Mauretanien",
            "code":"MR"
        },
        {
            "name":"Mauritius",
            "code":"MU"
        },
        {
            "name":"Mayotte",
            "code":"YT"
        },
        {
            "name":"Mexiko",
            "code":"MX"
        },
        {
            "name":"Mikronesien",
            "code":"FM"
        },
        {
            "name":"Moldawie",
            "code":"MD"
        },
        {
            "name":"Monaco",
            "code":"MC"
        },
        {
            "name":"Mongolei",
            "code":"MN"
        },
        {
            "name":"Montenegro",
            "code":"ME"
        },
        {
            "name":"Montserrat",
            "code":"MS"
        },
        {
            "name":"Marokko",
            "code":"MA"
        },
        {
            "name":"Mosambik",
            "code":"MZ"
        },
        {
            "name":"Myanmar",
            "code":"MM"
        },
        {
            "name":"Namibia",
            "code":"NA"
        },
        {
            "name":"Nauru",
            "code":"NR"
        },
        {
            "name":"Népal",
            "code":"NP"
        },
        {
            "name":"Niederlande",
            "code":"NL"
        },
        {
            "name":"Neukaledonien",
            "code":"NC"
        },
        {
            "name":"Neuseeland",
            "code":"NZ"
        },
        {
            "name":"Nicaragua",
            "code":"NI"
        },
        {
            "name":"Niger",
            "code":"NE"
        },
        {
            "name":"Nigeria",
            "code":"NG"
        },
        {
            "name":"Niue",
            "code":"NU"
        },
        {
            "name":"Norfolkinsel",
            "code":"NF"
        },
        {
            "name":"Nordkorea",
            "code":"KP"
        },
        {
            "name":"Nördliche Marianen",
            "code":"MP"
        },
        {
            "name":"Norwegen",
            "code":"NO"
        },
        {
            "name":"Oman",
            "code":"OM"
        },
        {
            "name":"Pakistan",
            "code":"PK"
        },
        {
            "name":"Palau",
            "code":"PW"
        },
        {
            "name":"Palästina",
            "code":"PS"
        },
        {
            "name":"Panama",
            "code":"PA"
        },
        {
            "name":"Papua-Neuguinea",
            "code":"PG"
        },
        {
            "name":"Paraguay",
            "code":"PY"
        },
        {
            "name":"Peru",
            "code":"PE"
        },
        {
            "name":"Philippinen",
            "code":"PH"
        },
        {
            "name":"Pitcairn",
            "code":"PN"
        },
        {
            "name":"Polen",
            "code":"PL"
        },
        {
            "name":"Portugal",
            "code":"PT"
        },
        {
            "name":"Puerto Rico",
            "code":"PR"
        },
        {
            "name":"Katar",
            "code":"QA"
        },
        {
            "name":null,
            "code":"XK"
        },
        {
            "name":"Réunion",
            "code":"RE"
        },
        {
            "name":"Rumänien",
            "code":"RO"
        },
        {
            "name":"Russland",
            "code":"RU"
        },
        {
            "name":"Ruanda",
            "code":"RW"
        },
        {
            "name":"Saint-Barthélemy",
            "code":"BL"
        },
        {
            "name":"Sankt Helena",
            "code":"SH"
        },
        {
            "name":"St. Kitts und Nevis",
            "code":"KN"
        },
        {
            "name":"Saint Lucia",
            "code":"LC"
        },
        {
            "name":"Saint Martin",
            "code":"MF"
        },
        {
            "name":"Saint-Pierre und Miquelon",
            "code":"PM"
        },
        {
            "name":"Saint Vincent und die Grenadinen",
            "code":"VC"
        },
        {
            "name":"Samoa",
            "code":"WS"
        },
        {
            "name":"San Marino",
            "code":"SM"
        },
        {
            "name":"São Tomé und Príncipe",
            "code":"ST"
        },
        {
            "name":"Saudi-Arabien",
            "code":"SA"
        },
        {
            "name":"Senegal",
            "code":"SN"
        },
        {
            "name":"Serbien",
            "code":"RS"
        },
        {
            "name":"Seychellen",
            "code":"SC"
        },
        {
            "name":"Sierra Leone",
            "code":"SL"
        },
        {
            "name":"Singapur",
            "code":"SG"
        },
        {
            "name":"Sint Maarten (niederl. Teil)",
            "code":"SX"
        },
        {
            "name":"Slowakei",
            "code":"SK"
        },
        {
            "name":"Slowenien",
            "code":"SI"
        },
        {
            "name":"Salomonen",
            "code":"SB"
        },
        {
            "name":"Somalia",
            "code":"SO"
        },
        {
            "name":"Republik Südafrika",
            "code":"ZA"
        },
        {
            "name":"Südgeorgien und die Südlichen Sandwichinseln",
            "code":"GS"
        },
        {
            "name":"Südkorea",
            "code":"KR"
        },
        {
            "name":"Südsudan",
            "code":"SS"
        },
        {
            "name":"Spanien",
            "code":"ES"
        },
        {
            "name":"Sri Lanka",
            "code":"LK"
        },
        {
            "name":"Sudan",
            "code":"SD"
        },
        {
            "name":"Suriname",
            "code":"SR"
        },
        {
            "name":"Svalbard und Jan Mayen",
            "code":"SJ"
        },
        {
            "name":"Swasiland",
            "code":"SZ"
        },
        {
            "name":"Schweden",
            "code":"SE"
        },
        {
            "name":"Schweiz",
            "code":"CH"
        },
        {
            "name":"Syrien",
            "code":"SY"
        },
        {
            "name":"Taiwan",
            "code":"TW"
        },
        {
            "name":"Tadschikistan",
            "code":"TJ"
        },
        {
            "name":"Tansania",
            "code":"TZ"
        },
        {
            "name":"Thailand",
            "code":"TH"
        },
        {
            "name":"Timor-Leste",
            "code":"TL"
        },
        {
            "name":"Togo",
            "code":"TG"
        },
        {
            "name":"Tokelau",
            "code":"TK"
        },
        {
            "name":"Tonga",
            "code":"TO"
        },
        {
            "name":"Trinidad und Tobago",
            "code":"TT"
        },
        {
            "name":"Tunesien",
            "code":"TN"
        },
        {
            "name":"Türkei",
            "code":"TR"
        },
        {
            "name":"Turkmenistan",
            "code":"TM"
        },
        {
            "name":"Turks- und Caicosinseln",
            "code":"TC"
        },
        {
            "name":"Tuvalu",
            "code":"TV"
        },
        {
            "name":"Uganda",
            "code":"UG"
        },
        {
            "name":"Ukraine",
            "code":"UA"
        },
        {
            "name":"Vereinigte Arabische Emirate",
            "code":"AE"
        },
        {
            "name":"Vereinigtes Königreich",
            "code":"GB"
        },
        {
            "name":"Vereinigte Staaten von Amerika",
            "code":"US"
        },
        {
            "name":"Uruguay",
            "code":"UY"
        },
        {
            "name":"Usbekistan",
            "code":"UZ"
        },
        {
            "name":"Vanuatu",
            "code":"VU"
        },
        {
            "name":"Venezuela",
            "code":"VE"
        },
        {
            "name":"Vietnam",
            "code":"VN"
        },
        {
            "name":"Wallis und Futuna",
            "code":"WF"
        },
        {
            "name":"Westsahara",
            "code":"EH"
        },
        {
            "name":"Jemen",
            "code":"YE"
        },
        {
            "name":"Sambia",
            "code":"ZM"
        },
        {
            "name":"Simbabwe",
            "code":"ZW"
        }
    ],
    "qualifikationen":[
        {
            "id":1,
            "str":"Öffentlich bestellt und vereidigt"
        },
        {
            "id":2,
            "str":"Zertifiziert nach 17024"
        },
        {
            "id":3,
            "str":"Zertifiziert"
        },
        {
            "id":4,
            "str":"Staatlich anerkannt"
        },
        {
            "id":5,
            "str":"Sonstige"
        }
    ],
    "objektTypen": [
        "Bankgebäude",
        "Bürogebäude",
        "Doppelhaushälfte",
        "Eigentumswohnung",
        "Freistehendes Einfamilienhaus",
        "Freistehendes Zweifamilienhaus",
        "Freistehendes Dreifamilienhaus",
        "Einfamilienhaus",
        "Einfamilienhaus Neubau",
        "Zweifamilienhaus",
        "Zweifamilienhaus Neubau",
        "Dreifamilienhaus",
        "Dreifamilienhaus Neubau",
        "Garage",
        "Wohnunseigentümergemeinschaft",
        "Geschäftshaus",
        "Mehrfamilienhaus",
        "Reihenendhaus",
        "Reihenmittelhaus",
        "Wohn-/ Geschäftshaus",
        "Sonstige"
    ]
}

if(typeof module !== "undefined")
    module.exports.globalData = globalData;